### PR TITLE
WIP: make RFTools screens take our variable cards

### PR DESCRIPTION
**Pull request by josephcsible**
This isn't even close to ready to merge yet. I'm only putting it here for easy review of what I have so far.

Things I need to do/check myself:
- [ ] Fix code formatting/style
- [ ] Don't let very long strings render off the end of the screen
- [ ] Add configuration like color of the displayed text
- [ ] If the variable card has a label, render it
- [ ] Make sure it's normal that screenData is briefly null when loading a saved game, and if so, clean up the message about it
- [ ] Possibly make the RF/tick configurable
- [x] Take out the code that disables a bunch of other compats (just there for now as a convenient workaround for #4)
- [ ] If something like a block is passed, have the option to render the image of the block instead of its name
- [ ] Make sure missing a network is handled sanely

Things I need assistance with/review of:
- [ ] Make sure that the 3 capabilities I add in CableNetworkCapabilityProvider (CableConfig.CAPABILITY, NetworkCarrierConfig.CAPABILITY, PathElementConfig.CAPABILITY) are the right ones to put a part on the network
- [ ] Handle calls to updateConnections() better (in our TileEntities, we call this when the TileEntity is ticked, but I don't think we have that ability when attaching to other mods' TileEntities)
- [ ] When a new screen is placed next to an existing cable, make it connect
- [ ] Make sure I implemented CableScreen.sendUpdate correctly (all other implementations call a method from CyclopsTileEntity, which isn't available on RFTools' tile entities)
- [ ] Should I be materializing the value before I send it to the client? I think so

### CODE REVIEW

**Comment by josephcsible** [comment]
Things I see looking at BlockCable:
* It calls CableHelpers.onCableRemoving from the 3-argument form of onPreBlockDestroyed. It's eventually called from three places:
  * Explosion.doExplosionB. ExplosionEvent.Detonate will let us hook this.
  * PlayerControllerMP.onPlayerDestroyBlock. PlayerInteractEvent.LeftClickBlock will let us hook this, with the possible exception of the path from onPlayerDamageBlock, but this looks like a client-only path anyway.
  * PlayerInteractionManager.tryHarvestBlock. BlockEvent.BreakEvent will let us hook this.
* It calls CableHelpers.onCableRemoving from the 2-argument form of onPreBlockDestroyed. It's eventually called from World.setBlockState. **I don't see any way to hook this.**
* It calls CableHelpers.onCableRemoved from onPostBlockDestroyed. This is eventually called from:
  * World.setBlockState. **Again, I don't see any way to hook this.**
  * Explosion.doExplosionB. **There doesn't seem to be any event that fires after the blocks are gone (Detonate fires before).**
* It calls CableHelpers.onCableAdded from onBlockPlacedBy. This is eventually called from ItemStack.onItemUse. PlaceEvent and MultiPlaceEvent *may* let us hook this.
* It calls NetworkHelpers.onElementProviderBlockNeighborChange from neighborChanged. NeighborNotifyEvent will let us hook this.

**Comment by rubensworks** [comment]
Adding those hooks seems to be too much of a hack. There has to be a better way to do this.

Some ideas:
1. We rewrite all cable-placement logic to make this more easily doable. This would require *a lot* of refactoring, so not ideal.
2. We add some kind of *Cable Interface* that can be placed against an RFTools screen. Our RFTools capability could then look for such interfaces as neighbours, and properly interact with the network that way.
3. We don't support RFTools screens at all.

At the moment, I think option 2 is the most feasible one, but we'd have to look into the details first before going this route.

**Comment by josephcsible** [comment]
I think 1 might be a better long-term solution, since there's bound to be more mods with blocks that would be useful to make part of our networks.

**Comment by rubensworks** [comment]
Now that I think of it, not sure if 1 is even possible.
With the `CableHelpers`, a lot of cable placement and breaking logic has already been abstracted. So I'm not sure if the cable logic can be refactored to make this even simpler.

Perhaps an experimental branch could be started for this, just to see what can be done.

**Comment by rubensworks** [comment]
Closing due to inactivity.

**Pull request closed without merging**
